---
abstract: ...
author:
  - 'DERIV <DERIV@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::More: '0.98'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '7.64'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.025, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Release4
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  Test::Release4:
    file: lib/Test/Release4.pm
    version: '0.002'
requires:
  indirect: '0.37'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/chylli-binary/tm-test4/issues
  homepage: https://github.com/chylli-binary/tm-test4
  repository: https://github.com/chylli-binary/tm-test4.git
version: '0.002'
x_authority: cpan:DERIV
x_contributors:
  - 'chylli-binary <chylli@binary.com>'
  - 'circleci <circleci@binary.com>'
x_generated_by_perl: v5.34.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
